stages:
  - style
  - test

.base:
  only:
    refs:
      - main
      - merge_requests

.style:
  extends: ".base"
  image: "python:3.6"

lint:
  stage: style
  extends: ".style"
  before_script:
    - pip install flake8
  script:
    - flake8

black-format:
  stage: style
  extends: ".style"
  before_script:
    - pip install black
  script:
    - LC_ALL=C.UTF-8 black --check --safe .

.test:
  stage: test
  extends: ".base"
  before_script:
    - pip install pytest-cov
  script:
    - pip install .[test]
    - pytest --cov=./ .

test-3.6:
    extends: ".test"
    image: "python:3.6"

test-3.7:
    extends: ".test"
    image: "python:3.7"

test-3.8:
    extends: ".test"
    image: "python:3.8"

test-3.9:
    extends: ".test"
    image: "python:3.9"
