include:
  - project: dau/ci/pyci
    file: .gitlab-ci-template.yml

variables:
  WARNING1: "ignore::DeprecationWarning:ansiwrap.core"
  WARNING2: "ignore::DeprecationWarning:jupyter_client.session"
  WARNING3: "ignore::DeprecationWarning:traitlets.traitlets"

test-3.7:
  extends: .test-3.7
  variables:
    JUPYTER_PLATFORM_DIRS: "1" # jupyter_client deprecation warning
    PYTEST_WARNINGS: "-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3}"

test-3.8:
  extends: .test-3.8
  variables:
    JUPYTER_PLATFORM_DIRS: "1" # jupyter_client deprecation warning
    PYTEST_WARNINGS: "-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3}"

test-3.9:
  extends: .test-3.9
  variables:
    JUPYTER_PLATFORM_DIRS: "1" # jupyter_client deprecation warning
    PYTEST_WARNINGS: "-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3}"

test-3.8-examples:
  extends: .test-3.8
  variables:
    JUPYTER_PLATFORM_DIRS: "1" # jupyter_client deprecation warning
    PYTEST_WARNINGS: "-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3}"

test-3.10-win:
  extends: .test-3.10-win
  variables:
    JUPYTER_PLATFORM_DIRS: "1" # jupyter_client deprecation warning
    PYTEST_WARNINGS: "-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3}"

build_sdist:
  extends: .build_sdist

test_sdist-3.12:
  extends: .test_sdist-3.12
  variables:
    JUPYTER_PLATFORM_DIRS: "1" # jupyter_client deprecation warning
    PYTEST_WARNINGS: "-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3}"

test_sdist-3.8-win:
  extends: .test_sdist-3.8-win
  variables:
    JUPYTER_PLATFORM_DIRS: "1" # jupyter_client deprecation warning
    PYTEST_WARNINGS: "-W error -W ${WARNING1} -W ${WARNING2} -W ${WARNING3}"

build_doc:
  extends: .build_doc

pages:
  extends: .pages

assets:
  extends: .assets
